import {
  Flex,
  Box,
  Text,
  Heading,
  Button,
  Image,
  VStack,
  HStack,
  Link,
} from "@chakra-ui/react";
import { FaArrowRight } from "react-icons/fa";
import FeatureCards from "~/components/home/FeatureCards";
import FooterCTA from "~/components/home/FooterCTA";
import LoginPrompt from "~/components/home/LoginPrompt";
import PostTypeIcons from "~/components/home/PostTypeIcons";
import VIPprompt from "~/components/home/VIPprompt";
import { links } from "~/root";
import EarningsCalculator from "./calculator";
const buttonStyle = {
  color: "#111",
  background: "#fff",
  px: "15px",
  gap: "8px",
  py: "10px",
  borderRadius: "10px",
  alignItems: "center",
  justifyContent: "center",
  width: "190px",
};
const textStyle = {
  fontSize: "18px",
  fontWeight: "600",
};
const iconStyle = {
  fontSize: "28px",
  color: "#fff",
};

export default function DJhome() {
  return (
    <Flex w="100%" h="100%" minH="100vh" flexDirection="column">
      <Box
        as="nav"
        role="navigation"
        position="sticky"
        top="0"
        zIndex="docked"
        bg="black"
        borderBottom="1px solid #ffffff"
        w="100%"
        display="flex"
        justifyContent="center"
        py="10px"
      >
        <Box as="a" href="/">
          <Image
            id="logo"
            w="120px"
            src="https://files.djfan.app/images/djfan-beta.png"
          />
        </Box>
      </Box>
      <Box w="100%" display={"flex"} justifyContent={"center"}>
        <VStack
          w="100%"
          maxW="700px"
          alignItems="flex-start"
          px={{ base: "15px", md: "10px" }}
          pt={{ base: "20px", md: "30px" }}
          pb={{ base: "30px", md: "50px" }}
          gap="5px"
        >
          <Heading fontSize={"20px"} pb="10px">
            Partner Program Terms and Conditions
          </Heading>
          <Heading fontSize={"16px"} lineHeight="1em">
            1. Introduction
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            This document outlines the terms and conditions of the Partner
            Program (&quot;Program&quot;) offered by DJfan. By participating in
            the Program, you (&quot;Partner&quot;) agree to abide by these terms
            and conditions.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            2. Affiliate Link
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            Upon registration to the Program, Partners will be given a unique
            invitation link (&quot;Affiliate Link&quot;). This link should be
            shared with potential users to invite them to join DJfan.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            3. Referrals
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            A &quot;Referral&quot; is defined as a user who joins DJfan using a
            Partner&apos;s Affiliate Link. Referrals must be real individuals
            who meet our platform&apos;s eligibility criteria.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            4. Referral Earnings
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            Partners will earn a commission of 5% (&quot;Referral
            Earnings&quot;) of all income generated by their Referrals. The
            calculation of this income will include all revenues generated by
            the Referral, excluding any taxes, chargebacks, refunds, or
            fraudulent transactions.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            5. Payouts
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            Referral Earnings will be paid out on a monthly basis, or when the
            Partner&apos;s accrued earnings reach a minimum threshold, as
            defined by DJfan. Payout method and any associated processing fees
            will be communicated to the Partner ahead of time.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            6. Partner Dashboard
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            Partners will have access to a Partner Dashboard, where they can
            monitor their Referrals, Referral Earnings, and upcoming Payouts.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            7. Qualified Earnings
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            &quot;Qualified Earnings&quot; are the portion of a Referral&apos;s
            income that are eligible for the Partner&apos;s commission. This
            includes all revenues generated by the Referral, excluding any
            taxes, chargebacks, refunds, or fraudulent transactions.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            8. Termination
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            Partners may be removed from the Program at any time, for any
            reason, at the discretion of DJfan. Grounds for termination may
            include, but are not limited to, fraudulent activity, violation of
            DJfan&apos;s Terms of Service, or failure to generate any Referrals
            over an extended period.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            9. Fraudulent Activity
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            Any attempt to manipulate the system, create false Referrals, or
            otherwise engage in dishonest practices will be considered
            &quot;Fraudulent Activity&quot; and may result in immediate
            termination from the Program and forfeit of any earned commissions.
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            10. Payment Threshold
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            The &quot;Payment Threshold&quot; is the minimum amount of Referral
            Earnings a Partner must accrue before they can receive a payout. The
            Payment Threshold is subject to change at the discretion of [Your
            Creator Platform].
          </Text>
          <Heading fontSize={"16px"} lineHeight="1em">
            11. Modifications to Terms
          </Heading>
          <Text fontSize={"14px"} pb="10px">
            DJfan reserves the right to modify these terms at any time. Any
            changes will be communicated to Partners in a timely manner.
          </Text>
          <Text fontSize={"14px"} pb="10px">
            By signing up to participate in the Program, you acknowledge that
            you have read, understood, and agreed to these terms and conditions.
            If you do not agree with any part of these terms, you should not
            participate in the Program.
          </Text>
          <Link
            fontSize={"14px"}
            fontWeight="bold"
            href="/terms"
            color={"#7d5aeb"}
          >
            See terms for all users
          </Link>
        </VStack>
      </Box>

      <Flex
        py="15px"
        fontSize="12px"
        justifyContent="center"
        bg="#111"
        color="#fff"
        textAlign={"center"}
      >
        © 2023 DJfan Ltd.
        <br /> 1 Quality Court, Chancery Lane, London, WC2A 1HR
      </Flex>
    </Flex>
  );
}
